env:
  node: true
  es6: true

extends:
  - airbnb-base
  - prettier

rules:
  max-len:
    - error
    - 80
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true

  no-param-reassign: off

  no-restricted-syntax:
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement
