extends:
  - stylelint-config-standard
  - stylelint-config-prettier

ignoreFiles:
  - coverage/**/*
  - docs/style/**/*
  - jsdoc/**/*

plugins:
  - stylelint-scss

rules:
  at-rule-no-unknown:
    - null
  scss/at-rule-no-unknown:
    - true
